project:
  type: website
  output-dir: docs

website:
  title: "Current Projects"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ww357
      - icon: linkedin
        href: https://linkedin.comwww.linkedin.com/in/william-ward-463493245
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

